import { ModuleWithProviders, NgModule,
         Optional, SkipSelf } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule }  from '@angular/forms';
import { 
          MdAutocompleteModule,
          MdCheckboxModule,       
          MdDatepickerModule,
          MdInputModule,
          MdRadioModule,
          MdSelectModule,
          MdSliderModule,
          MdSlideToggleModule,
          MdMenuModule,
          MdSidenavModule,
          MdToolbarModule,
          MdListModule,
          MdGridListModule,
          MdCardModule,
          MdTabsModule,   
          MdButtonModule,
          MdButtonToggleModule,
          MdChipsModule,
          MdIconModule,
          MdProgressSpinnerModule,
          MdProgressBarModule,                    
          MdDialogModule,
          MdTooltipModule,
          MdSnackBarModule,
          MdTableModule,
          MdSortModule,
          MdPaginatorModule        
      } from '@angular/material';
import { Hall } from './models/hall';
import { Reservation} from './models/reservation';

@NgModule({
  imports: [
    CommonModule, 
    MdAutocompleteModule,
    MdCheckboxModule,       
    MdDatepickerModule,
    MdInputModule,
    MdRadioModule,
    MdSelectModule,
    MdSliderModule,
    MdSlideToggleModule,
    MdMenuModule,
    MdSidenavModule,
    MdToolbarModule,
    MdListModule,
    MdGridListModule,
    MdCardModule,
    MdTabsModule,   
    MdButtonModule,
    MdButtonToggleModule,
    MdChipsModule,
    MdIconModule,
    MdProgressSpinnerModule,
    MdProgressBarModule,                    
    MdDialogModule,
    MdTooltipModule,
    MdSnackBarModule,
    MdTableModule,
    MdSortModule,
    MdPaginatorModule   
  ],
  declarations: [  ],
  exports: [
    CommonModule, 
    FormsModule, 
    ReactiveFormsModule, 
    MdAutocompleteModule,
    MdCheckboxModule,       
    MdDatepickerModule,
    MdInputModule,
    MdRadioModule,
    MdSelectModule,
    MdSliderModule,
    MdSlideToggleModule,
    MdMenuModule,
    MdSidenavModule,
    MdToolbarModule,
    MdListModule,
    MdGridListModule,
    MdCardModule,
    MdTabsModule,   
    MdButtonModule,
    MdButtonToggleModule,
    MdChipsModule,
    MdIconModule,
    MdProgressSpinnerModule,
    MdProgressBarModule,                    
    MdDialogModule,
    MdTooltipModule,
    MdSnackBarModule,
    MdTableModule,
    MdSortModule,
    MdPaginatorModule
  ]
})
export class SharedModule { }
